[theme]
name = 'Google Cursor'
comment = 'An opensource cursor theme inspired by Google.'
website = 'https://github.com/ful1e5/Google_Cursor'

[config]
bitmaps_dir = '' # This config will assigned with `ctgen -d <path>`
out_dir = 'themes'
platforms = ['x11', 'windows']
x11_sizes = [22, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
win_size = 32

[cursors]

[cursors.fallback_settings]
x_hotspot = 100
y_hotspot = 100
x11_delay = 10
win_delay = 1